server:
  port: 8001


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.qt.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservice-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.127/springcloud_db01?serverTimezone=GMT%2B8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
